### ISSUE TITLE
To-do back

### ISSUE THREAD

**Issue by lMagickl** [lMagickl/lic-pro-2019-project#1]
- [x] [BACK] [ Refractor le code]
- [ ] [BACK/FRONT] [ Gestion des exceptions ]
- [ ] [BACK/FRONT] [ Gestions des codes d'erreurs ] 
- [x] [BACK] gerer l'indentation des fichiers json
- [ ] [BACK] gerer la creatio du dossier episode si c'est le premier
- [ ] [FRONT] gerer l'erreur après suppression
